name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET 10 SDK
        user: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x
      - name: Restore API
        run: dotnet restore ./src/api/api.csproj
      - name: Build API
        run: dotnet build ./src/api/api.csproj --no-restore
      - name: Test API
        run: dotnet test ./src/api/api.csproj --no-build --verbosity normal